name: Terraform Apply

on:
 workflow_dispatch:
 
jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    - run: Mostrando
      echo 


    
